server:
  port: 9090

spring:
  application:
    name: NettyServer
  boot:
    admin:
      client:
        url: http://localhost:9000

# 暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
netty:
  port: 11011

